"""t2

Revision ID: 8a8d0d79c6da
Revises: fcf232267ba4
Create Date: 2026-02-11 16:00:11.257764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8d0d79c6da'
down_revision: Union[str, Sequence[str], None] = 'fcf232267ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###












#     YES — upgrade() and downgrade() are connected. VERY closely.

# They always come in a pair, like:

# Do something → undo the same thing

# Add something → remove that same thing

# Go forward → go backward

# They are created together in every migration file.

# 🌟 HOW THEY ARE RELATED
# ✔ 1. upgrade() = apply the change
# ✔ 2. downgrade() = reverse the same change

# Example:

# upgrade():
# add age column

# downgrade():
# remove age column
# So:

# Downgrade always does the opposite of upgrade

# Downgrade cannot exist without upgrade

# Upgrade cannot be undone without downgrade

# 🌟 PERFECT RELATIONSHIP EXAMPLE
# 🔹 If upgrade() creates a table
# downgrade() must drop that same table.

# 🔹 If upgrade() adds a column
# downgrade() must drop that same column.

# 🔹 If upgrade() changes column name
# downgrade() must rename it back
# If upgrade() changes column name

# downgrade() must rename it back.

# 🔹 If upgrade() deletes something

# downgrade() must add it back.

# 🌟 WHY THEY MUST MATCH?

# Because Alembic must know:

# Action	What if we want to undo it?
# upgrade	use downgrade
# +1 version	-1 version
# apply changes	remove changes
# forward direction	backward direction

# It’s like:
# You write something on paper

# ➡ upgrade()

# You erase exactly that thing

# ➡ downgrade()
